using DocumentFormat.OpenXml.Packaging;

[TestFixture]
public class DocumentPropertiesTests
{
    [Test]
    public async Task RoundTrip_DocumentProperties()
    {
        #region DocumentPropertiesUsage

        var builder = new BookBuilder();
        builder.AddSheet(SampleData.Employees());
        builder.SetProperties(
            new()
            {
                Title = "Q1 staff snapshot",
                Author = "Simon",
                Subject = "Headcount",
                Keywords = "staff, q1",
                Comments = "Generated by Excelsior",
                Category = "HR",
                Status = "Final",
                LastModifiedBy = "Simon",
                Company = "Papyrine",
                Manager = "Jane",
                Custom =
                {
                    ["Project"] = "Excelsior",
                    ["Reviewed"] = true,
                    ["Revision"] = 3,
                    ["Score"] = 9.5,
                    ["GeneratedAt"] = new DateTime(2026, 1, 15, 9, 30, 0, DateTimeKind.Utc)
                }
            });

        using var stream = await builder.ToMemoryStream();

        #endregion

        // ToMemoryStream clones the package, so verifying the reopened stream proves the
        // properties survive the clone rather than only existing on the in-memory document.
        using var document = SpreadsheetDocument.Open(stream, false);
        await Verify(document);
    }

    [Test]
    public async Task SetProperties_LastCallWins()
    {
        var builder = new BookBuilder();
        builder.AddSheet(SampleData.Employees());
        builder.SetProperties(new() { Title = "first" });
        builder.SetProperties(new() { Title = "second" });

        using var stream = await builder.ToMemoryStream();
        using var document = SpreadsheetDocument.Open(stream, false);

        Assert.That(document.PackageProperties.Title, Is.EqualTo("second"));
    }

    [Test]
    public void SetProperties_UnsupportedCustomType_Throws()
    {
        var builder = new BookBuilder();
        builder.AddSheet(SampleData.Employees());
        builder.SetProperties(
            new()
            {
                Custom =
                {
                    ["Bad"] = new()
                }
            });

        // The unsupported value is only encountered when the workbook is built.
        var exception = Assert.ThrowsAsync<ArgumentException>(async () => await builder.ToMemoryStream());
        Assert.That(exception!.Message, Does.Contain("Bad").And.Contain("System.Object"));
    }
}
