using DocumentFormat.OpenXml.Packaging;

public class DocumentPropertiesTests
{
    [Test]
    public async Task RoundTrip_DocumentProperties()
    {
        #region DocumentPropertiesUsage

        var builder = new BookBuilder();
        builder.AddSheet(SampleData.Employees());
        builder.SetProperties(
            new()
            {
                Title = "Q1 staff snapshot",
                Author = "Simon",
                Subject = "Headcount",
                Keywords = "staff, q1",
                Comments = "Generated by Excelsior",
                Category = "HR",
                Status = "Final",
                LastModifiedBy = "Simon",
                Company = "Papyrine",
                Manager = "Jane",
                Custom =
                {
                    ["Project"] = "Excelsior",
                    ["Reviewed"] = true,
                    ["Revision"] = 3,
                    ["Score"] = 9.5,
                    ["GeneratedAt"] = new DateTime(2026, 1, 15, 9, 30, 0, DateTimeKind.Utc),
                    ["DatasetId"] = new Guid("9b8a7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d")
                }
            });

        using var stream = await builder.ToMemoryStream();

        #endregion

        // ToMemoryStream clones the package, so verifying the reopened stream proves the
        // properties survive the clone rather than only existing on the in-memory document.
        using var document = SpreadsheetDocument.Open(stream, false);
        await Verify(document);
    }

    [Test]
    public async Task SetProperties_LastCallWins()
    {
        var builder = new BookBuilder();
        builder.AddSheet(SampleData.Employees());
        builder.SetProperties(new() { Title = "first" });
        builder.SetProperties(new() { Title = "second" });

        using var stream = await builder.ToMemoryStream();
        using var document = SpreadsheetDocument.Open(stream, false);

        await Assert.That(document.PackageProperties.Title).IsEqualTo("second");
    }

    [Test]
    public async Task SetProperties_UnsupportedCustomType_Throws()
    {
        var builder = new BookBuilder();
        builder.AddSheet(SampleData.Employees());
        builder.SetProperties(
            new()
            {
                Custom =
                {
                    ["Bad"] = new()
                }
            });

        // The unsupported value is only encountered when the workbook is built.
        var exception = await Assert.That(async () => await builder.ToMemoryStream()).ThrowsExactly<ArgumentException>();
        await Assert.That(exception!.Message).Contains("Bad").And.Contains("System.Object");
    }

    // Reading a property without a Convert: the sheets are never parsed, so an upload can be routed
    // by an embedded id without paying for the whole workbook.
    [Test]
    public async Task ReadCustomPropertiesWithoutParsingSheets()
    {
        var datasetId = new Guid("9b8a7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d");

        var builder = new BookBuilder();
        builder.AddSheet(SampleData.Employees());
        builder.SetProperties(
            new()
            {
                Custom =
                {
                    ["DatasetId"] = datasetId,
                    ["Project"] = "Excelsior"
                }
            });

        using var stream = await builder.ToMemoryStream();

        #region ReadCustomPropertiesStandalone

        var properties = BookReader.ReadCustomProperties(stream);

        #endregion

        using (Assert.Multiple())
        {
            await Assert.That(properties["DatasetId"]).IsEqualTo(datasetId.ToString());
            await Assert.That(properties["Project"]).IsEqualTo("Excelsior");
            // Case-insensitive, matching the instance members.
            await Assert.That(properties["datasetid"]).IsEqualTo(datasetId.ToString());
        }
    }

    // A workbook with no custom part reads as empty rather than throwing.
    [Test]
    public async Task ReadCustomPropertiesWhenNoneWereSet()
    {
        var builder = new BookBuilder();
        builder.AddSheet(SampleData.Employees());
        using var stream = await builder.ToMemoryStream();

        await Assert.That(BookReader.ReadCustomProperties(stream)).IsEmpty();
    }

    [Test]
    public async Task ReadCustomProperties()
    {
        #region ReadCustomProperties

        var datasetId = new Guid("9b8a7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d");

        var builder = new BookBuilder();
        builder.AddSheet(SampleData.Employees());
        builder.SetProperties(
            new()
            {
                Custom =
                {
                    ["DatasetId"] = datasetId,
                    ["Project"] = "Excelsior",
                    ["Revision"] = 3,
                    ["Reviewed"] = true,
                    ["Score"] = 9.5
                }
            });

        using var stream = await builder.ToMemoryStream();

        var reader = new BookReader();
        reader.AddSheet<Employee>();
        reader.Convert(stream);

        // The type argument drives the conversion: a Guid is parsed back from its text form.
        var id = reader.GetCustomProperty<Guid>("DatasetId");
        var revision = reader.GetCustomProperty<int>("Revision");

        #endregion

        using (Assert.Multiple())
        {
            await Assert.That(id).IsEqualTo(datasetId);
            await Assert.That(revision).IsEqualTo(3);
            await Assert.That(reader.GetCustomProperty<string>("Project")).IsEqualTo("Excelsior");
            await Assert.That(reader.GetCustomProperty<bool>("Reviewed")).IsTrue();
            await Assert.That(reader.GetCustomProperty<double>("Score")).IsEqualTo(9.5);
            // Names are matched case-insensitively, mirroring Excel and sheet-name lookup.
            await Assert.That(reader.GetCustomProperty<Guid>("datasetid")).IsEqualTo(datasetId);
        }
    }

    [Test]
    public async Task TryGetCustomProperty()
    {
        var builder = new BookBuilder();
        builder.AddSheet(SampleData.Employees());
        builder.SetProperties(new() { Custom = { ["Project"] = "Excelsior" } });
        using var stream = await builder.ToMemoryStream();

        var reader = new BookReader();
        reader.AddSheet<Employee>();
        reader.Convert(stream);

        using (Assert.Multiple())
        {
            await Assert.That(reader.TryGetCustomProperty<string>("Project", out var present)).IsTrue();
            await Assert.That(present).IsEqualTo("Excelsior");
            // Absent property.
            await Assert.That(reader.TryGetCustomProperty<string>("Missing", out _)).IsFalse();
            // Present, but its value is not convertible to the requested type.
            await Assert.That(reader.TryGetCustomProperty<Guid>("Project", out _)).IsFalse();
        }
    }

    [Test]
    public async Task GetCustomProperty_Missing_Throws()
    {
        var builder = new BookBuilder();
        builder.AddSheet(SampleData.Employees());
        builder.SetProperties(new() { Custom = { ["Project"] = "Excelsior" } });
        using var stream = await builder.ToMemoryStream();

        var reader = new BookReader();
        reader.AddSheet<Employee>();
        reader.Convert(stream);

        var exception = await Assert.That(() => reader.GetCustomProperty<string>("Missing")).ThrowsExactly<Exception>();
        await Assert.That(exception!.Message).Contains("Missing");
    }

    [Test]
    public async Task GetCustomProperty_BeforeConvert_Throws()
    {
        var reader = new BookReader();
        var exception = await Assert.That(() => reader.GetCustomProperty<Guid>("DatasetId")).ThrowsExactly<Exception>();
        await Assert.That(exception!.Message).Contains("Convert");
    }
}
