<Project>
  <Import Project="../src/Directory.Build.props" />
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="TUnit" Version="1.73.5" />
    <PackageVersion Include="Excelsior" Version="$(Version)" />
  </ItemGroup>
</Project>
