<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Argon" />
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="EmptyFiles" />
    <PackageReference Include="SimpleInfoName" />
    <PackageReference Include="Verify" />
    <PackageReference Include="Verify.SourceGenerators" />
    <PackageReference Include="TUnit" />
    <Using Include="TUnit.Assertions.Enums" />
    <ProjectReference Include="..\Excelsior\Excelsior.csproj" />
    <ProjectReference Include="..\Excelsior.SourceGenerator\Excelsior.SourceGenerator.csproj" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
  </ItemGroup>
</Project>
